### ISSUE TITLE
Support for pointer events

### ISSUE THREAD

**Issue by gnapse** [drag-drop-touch-js/dragdroptouch#5] opened 2017-04-11 19:35 UTC
There's this new standard for handling pointer events, that aims to unify work across all devices and types of pointer interfaces (mouse, touch, stylus, etc.): https://www.w3.org/TR/pointerevents/

It would be good for this library to support it. However, it is not yet supported in Safari, both desktop and mobile: http://caniuse.com/#search=pointer%20events. However, the motivation for supporting these events instead is because the touch events are not supported in IE-11/Edge on Microsoft Windows touch devices.

I was even meaning to start a pull-request of this repo and contribute this change myself, but given the lack of support of this feature in Apple devices, I decided to first ask here what do you think would be the best approach, or even if it's worth it. Perhaps I could attempt to detect if the browser supports pointer events, and use that, or else use touch events as it is today. What do you think?

**Comment by Bernardo-Castilho** [comment] 2017-04-11 19:39
Thanks for bringing this up. Fortunately, IE and Edge do support touch-based drag and drop on devices with touch screens, so the polyfill is not needed there.

**Comment by jboler** [comment] 2017-04-11 20:49
@Bernardo-Castilho I have a Surface Book and your demo page doesn't work on IE11 or Edge using the touch screen. This is because IE11/Edge doesn't support the touch events API, it only supports the pointer events API.

Your demo does work in Chrome on my Surface Book because Chrome supports both touch & pointer events.

Firefox is soon to enable their PointerEvents API implementation which will mean that all 4 major browsers on Windows have native Pointer Events support leaving only Safari iOS & Chrome Android that don't and there's a solid [polyfill](https://github.com/jquery/PEP) for those. I think the best way forward to support touch will be to use Pointer Events.

**Comment by Bernardo-Castilho** [comment] 2017-04-11 21:09
This is strange. I have a Surface with a regular touch screen, and the sample works for me:

  http://bernardo-castilho.github.io/DragDropTouch/demo/index.htm

In fact, the polyfill is not even needed in that case. The browser supports HTML5 drag/drop events by default.

I do like the Pointer events, and hope all browsers will support them soon, including drag/drop events.
When that happens, the world will be a better place, with cleaner and more standard code, and fewer polyfills ;-)

**Comment by gnapse** [comment] 2017-04-12 03:37
FWIW, I just tried this repo's demo page on IE 11 on a touch-enabled Windows laptop. The drag and drop works when using the touchpad, but not when attempting to drag and drop by interacting with the draggable elements via touching the screen.

**Comment by nicholaswmin** [comment] 2017-07-06 21:00
Chiming in to drop my 2 cents. If the device you are using has pen sensitivity then at least Chrome 59 will interpret the event as a `PointerEvent` and fail to propagate it/map it as a `MouseEvent`. The W3C stands

**Comment by Herst** [comment] 2017-07-21 12:05
I can confirm what @gnapse said, the demo page does not work in IE11 or Edge.

So I did some more testing with your demo and the demo with just the HTML 5 events (the native version, the one you used as a basis) and my own project where I only used the native events for now and I'm now trying to make compatible with more browers, there are two things I noticed:

* The native version does not work either in Edge either but it does work in my own project.

* The native version using mouse (or touchpad/trackpoint) does not work on IE11 (!). And in my own project dragging seems to work but not dropping (perhaps it has something to do with the code for making sure that the right stuff is being dragged into it).

(Newest IE11 and Edge on Win 10 with Creators Update on a touch-enabled device BTW.)

Apart from that it enables touch drag&drop in Chrome on Linux/Windows and Firefox on Windows where it previously wouldn't work with just native events (native with Firefox on Linux works when some requirements are met [GTK3, multi-process] which was the case for me).

**Comment by bbottema** [comment] 2018-02-22 18:41
The demo page doesn't work in Chrome either when it is in Responsive mode.

**Comment by frabie** [comment] 2019-04-26 13:06
It seems Google has dropped support of ontouch API in chrome release 70 www.chromestatus.com/feature/4764225348042752). This polyfill does not work anymore on touch enabled windows tablets with newer Chrome versions. As a workaround I would propose to change  the check whether touch is available in this way: `if (window.PointerEvent || 'ontouchstart' in document)`.

This works for me but it is still not perfect because it doesn´t solve the issue in Edge.

**Comment by Bernardo-Castilho** [comment] 2019-04-26 13:25
Did you try using navigator.maxTouchPoints as the article suggested?

BTW, most Edge issues should go away soon. I've been using the new Chromium-based version and it's great! ;-)

**Comment by frabie** [comment] 2019-04-26 15:48
`navigator.maxTouchPoints` standalone does not work in Firefox66.
On mobile devices the polyfill works parallel to the native browser implementation. Shorttouch activates the polyfill, longtouch activates the native implementation.

The best solution would be to find a way to disable this polyfill on mobile devices and using their own native browser implementations. E.g.  `if (window.orientation == undefined )` could solve this issue but it is deprecated and I don´t know how it works on chromebook tabs.

**Comment by Pomax** [comment] 2024-08-15 00:38
I'm closing this issue mostly because a lot of the code has changed since 2019, and the current version by default "just works" (in that it is no longer contingent on `navigator.maxTouchPoints`)

**Closed by Pomax** 2024-08-15 00:38 UTC
