### ISSUE TITLE
How to drag&drop from window A to window B in Android?

### ISSUE THREAD

**Issue by headwindtrend** [drag-drop-touch-js/dragdroptouch#60] opened 2023-11-19 19:55 UTC
i tried to use dragdroptouch to drag a thumbnail across windows (which is doable with mouse), but it doesn't work (drag&drop within the same webpage works fine). is it a limitation of html5 drag&drop api? if not, is it possible to add this feature to dragdroptouch? coz it would be super useful, to me at least.

**Comment by Bernardo-Castilho** [comment] 2023-11-20 02:35
I believe dragdroptouch should work exactly like regular drag drop.

This link discusses how to do html5 drag drop between apps and windows:

https://stackoverflow.com/questions/3694631/html5-drag-and-drop-between-windows

I hope it's helpful.

**Comment by headwindtrend** [comment] 2023-11-20 09:42
thank you for your reply. the referred stackoverflow post was talking about "drag&drop across windows" with mouse, i guess. yes, "drag&drop across windows" with mouse is working fine. my problem is, while dragdroptouch enabled me to drag&drop by touch-operation within a webpage, it doesn't seem to let me drag&drop across winfows by touch-operation. at least it doesn't work in my android smartphone that i had tried it out. whereas, on the same smartphone, "drag&drop across windows" with mouse is working fine. i hope i have illustrated the scenario a little better.

**Comment by Bernardo-Castilho** [comment] 2023-11-20 13:30
Like I said, I think if it works with the mouse then it should work with touch as well. Both use the same HTML5 events/methods/properties.

If that is not the case, please feel free to post a sample and I'll be happy to look at it.

Thanks.

**Comment by headwindtrend** [comment] 2023-11-21 07:57
right. please load the HTMLs below into different android browser windows. and see if you can drag the `testing` element from window A to window B by touch-operation. i can do it with mouse, but failed by touch-operation as supposed been enabled by dragdroptouch.

```
<script id="DragDropTouch" src="https://bernardo-castilho.github.io/DragDropTouch/DragDropTouch.js"></script>
window A<br><br>
<a href="#"><svg><rect width="300" height="200" style="cursor:pointer;fill:green"/><text x="50%" y="50%" dy=".3em" text-anchor="middle" style="font:bold 20px sans-serif;fill:white">testing</text></svg></a>
```

```
<script id="DragDropTouch" src="https://bernardo-castilho.github.io/DragDropTouch/DragDropTouch.js"></script>
<body ondragover="event.preventDefault()" ondrop="this.innerText=event.dataTransfer.getData('text/plain');">window B</body>
```
thanks.

**Comment by Bernardo-Castilho** [comment] 2023-11-21 19:48
Thanks for posting the sample.

I think I see what the problem is. You are using the **ondragover** and **ondrop** properties of the body element.

The **DragDropTouch** library does not call those methods when emulating the drag drop events. Instead, it fires regular events which should be handled with regular event listeners.

Also, it seems the code you sent relies on the fact that HTML5 sets the text content of the drag event automatically, which is also something the **DragDropTouch** library does not do.

The code below has a few minor changes that allow it to work with mouse and/or with touch:

```
<html>

  <head>
    <script id="DragDropTouch" src="https://bernardo-castilho.github.io/DragDropTouch/DragDropTouch.js"></script>

    <script>
      document.addEventListener("dragover", e => {
        e.preventDefault()
      });
      document.addEventListener("drop", e => {
        document.body.innerText = e.dataTransfer.getData("text/plain");
      });
      document.addEventListener("dragstart", e => {
        e.dataTransfer.setData("text/plain", e.target.href);
        //e.dataTransfer.setData("text/plain", "whatever you want");
      });
    </script>

  </head>

  <body>
    <p>
      window A
    </p>
    <p>
      <a href="#">
        <svg>
          <rect width="300" height="200" style="cursor:pointer;fill:green"/>
          <text x="50%" y="50%" dy=".3em" text-anchor="middle" style="font:bold 20px sans-serif;fill:white">testing</text>
        </svg>
      </a>
    </p>
    <p>
      window B
    </p>
  </body>
</html>
```

The code adds some event listeners to the **dragover**, **drop**, and **dragstart** events. **dragstart** is used to set the text/plain content of the data transfer object. The other events do the same thing as the original handlers did.

**Comment by headwindtrend** [comment] 2023-11-21 21:52
you can drag&drop across window by touch-operation with the html you provided above? i still cannot, my result is same as before, mouse can, touch cannot. im using a samsung galaxy device with google chrome for the testing. don't know if this makes a difference, though unlikely per normal guess.

**Comment by headwindtrend** [comment] 2023-11-21 22:15
i also tried it on win10 msedge, got the same result, mouse can, touch cannot.

**Comment by Bernardo-Castilho** [comment] 2023-11-22 05:38
Strange. I tried this in Chrome and also in Firefox 

I was able to drag from one browser to the other, and also from either browser to other instances of the same browser.

Strange...

**Comment by headwindtrend** [comment] 2023-11-22 09:15
if you have a working one, i should be able to make it work as well. just need to find out what makes the difference. i shot a video to show you what did it look like when i drag&drop it by touch, and by mouse thereafter. see if it can make you think of any suspects of the problem. thanks.
[dragdroptouch_testing.webm](https://github.com/Bernardo-Castilho/dragdroptouch/assets/128255279/2912dcde-89e1-483e-9df8-fb3cea6b7ca3)

**Comment by Bernardo-Castilho** [comment] 2023-11-24 03:11
Sorry, I tried again and it really didn't work with touch. I must have been dreaming, might have tested with the mouse and forgotten the problem was with touch...

I did a little quick research on this and found some suggestions, but none that worked so far.

I will look around some more to see if there's a way around thi.

Please accept my sincere apologies for the false/mistaken claim that it was working.

**Comment by Pomax** [comment] 2024-08-15 00:50
Based on recent testing in #77, which we managed to resolve, I'm closing this issue. If the original problem persists with the current version of the library, please file a new issues so we can look a that "afresh".

**Closed by Pomax** 2024-08-15 00:50 UTC
